import { SlideData, ThemePreset } from './types';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'emerald',
    name: 'Emerald Cyber (Default)',
    bg: '#05070a',
    fg: '#f4f7fa',
    primary: '#4fe5b0',
    accent: 'linear-gradient(115deg, #c8f56e 0%, #5aeeb0 42%, #34dcd8 74%, #29c0f0 100%)',
    surface: 'rgba(255, 255, 255, 0.045)',
    surface2: 'rgba(255, 255, 255, 0.07)',
    hair: 'rgba(255, 255, 255, 0.1)',
  },
  {
    id: 'indigo',
    name: 'Electric Indigo',
    bg: '#080a14',
    fg: '#f8fafc',
    primary: '#6366f1',
    accent: 'linear-gradient(115deg, #a855f7 0%, #6366f1 50%, #38bdf8 100%)',
    surface: 'rgba(255, 255, 255, 0.05)',
    surface2: 'rgba(255, 255, 255, 0.08)',
    hair: 'rgba(255, 255, 255, 0.12)',
  },
  {
    id: 'sunset',
    name: 'Sunset Orange',
    bg: '#0c0706',
    fg: '#fff7ed',
    primary: '#f97316',
    accent: 'linear-gradient(115deg, #fbbf24 0%, #f97316 50%, #f43f5e 100%)',
    surface: 'rgba(255, 255, 255, 0.05)',
    surface2: 'rgba(255, 255, 255, 0.08)',
    hair: 'rgba(255, 255, 255, 0.12)',
  },
  {
    id: 'luxury',
    name: 'Royal Gold',
    bg: '#0b0a08',
    fg: '#fefce8',
    primary: '#eab308',
    accent: 'linear-gradient(115deg, #fef08a 0%, #eab308 50%, #ca8a04 100%)',
    surface: 'rgba(255, 255, 255, 0.05)',
    surface2: 'rgba(255, 255, 255, 0.08)',
    hair: 'rgba(255, 255, 255, 0.12)',
  },
  {
    id: 'rose',
    name: 'Crimson Rose',
    bg: '#0d0608',
    fg: '#fff1f2',
    primary: '#f43f5e',
    accent: 'linear-gradient(115deg, #fda4af 0%, #f43f5e 50%, #e11d48 100%)',
    surface: 'rgba(255, 255, 255, 0.05)',
    surface2: 'rgba(255, 255, 255, 0.08)',
    hair: 'rgba(255, 255, 255, 0.12)',
  },
];

export const DEFAULT_SLIDES: SlideData[] = [
  {
    id: 's1',
    type: 'cover',
    nav: 'Pembuka',
    kicker: 'Mychiara Presentasi · 2026',
    title: 'Presentasi Interaktif Tanpa Coding',
    subtitle: 'Buat, sesuaikan teks, dan bagikan presentasi web modern langsung dari browser Anda.',
    foot: 'Gunakan tombol panah → atau Spasi untuk lanjut',
    notes: 'Sambutan pembuka kepada audiens. Jelaskan tujuan presentasi ini dibuat.',
  },
  {
    id: 's2',
    type: 'agenda',
    nav: 'Agenda',
    kicker: 'Ikhtisar Materi',
    title: 'Apa yang akan kita pelajari hari ini',
    items: [
      'Tantangan slide presentasi konvensional saat ini',
      'Solusi slide berbasis web modern & interaktif',
      'Keunggulan utama & fitur unggulan',
      'Langkah mudah memulai dan membagikan link',
    ],
    notes: 'Jelaskan poin-poin agenda secara ringkas dalam 1-2 menit.',
  },
  {
    id: 's3',
    type: 'statement',
    nav: 'Tantangan',
    kicker: 'Masalah Utama',
    title: 'Slide biasa terasa statis, membosankan, dan kaku di layar ponsel.',
    subtitle: 'Sudah saatnya beralih ke presentasi web yang responsif, hidup, dan bisa diakses dari mana saja.',
    notes: 'Tekankan rasa frustrasi audiens ketika membuka PPT di smartphone yang terpotong.',
  },
  {
    id: 's4',
    type: 'contrast',
    nav: 'Perbandingan',
    kicker: 'Perbandingan Solusi',
    title: 'Mengapa memilih slide interaktif?',
    leftKicker: 'Slide Biasa (PPT/PDF)',
    leftTitle: 'Terbatas & Statis',
    leftItems: [
      'Ukuran tetap 16:9 yang terpotong di HP',
      'File besar harus dikirim via email/chat',
      'Tidak bisa menampilkan animasi live atau web',
      'Sulit diperbarui saat ada revisi mendadak',
    ],
    rightKicker: 'Mychiara Sliders',
    rightTitle: 'Modern & Responsif',
    rightItems: [
      'Reflow otomatis menyesuaikan ukuran layar apa pun',
      'Cukup kirim 1 link URL langsung terbuka',
      'Presenter mode + coret layar (anotasi) bawaan',
      'Bisa diedit dan diperbarui kapan saja',
    ],
    notes: 'Bandingkan keuntungan nyata saat presentasi di depan klien.',
  },
  {
    id: 's5',
    type: 'bignumber',
    nav: 'Dampak',
    kicker: 'Hasil Nyata',
    title: 'Peningkatan Atensi Audiens',
    value: '85%',
    label: 'Audiens lebih fokus dan terlibat aktif saat presentasi menggunakan elemen interaktif.',
    sub: 'Survei efektivitas presentasi web 2026',
    notes: 'Tunjukkan angka ini dengan jeda dramatis.',
  },
  {
    id: 's6',
    type: 'bento',
    nav: 'Fitur',
    kicker: 'Kemampuan Platform',
    title: 'Semua alat yang Anda butuhkan',
    cards: [
      {
        kicker: 'Presenter Mode',
        title: 'Tab Khusus Presenter (P)',
        desc: 'Buka tab kedua dengan timer, catatan rahasia, dan intip slide selanjutnya tanpa terlihat audiens.',
      },
      {
        kicker: 'Interactive Annotation',
        title: 'Alat Coret Layar (A)',
        desc: 'Lingkari atau beri tanda pada angka penting saat berbicara secara langsung di layar.',
      },
      {
        kicker: 'No-Code Editor',
        title: 'Editor Visual Bawaan',
        desc: 'Ubah teks, judul, dan tema warna hanya dengan mengetik di panel samping tanpa coding.',
      },
      {
        kicker: 'One-Click Sharing',
        title: 'Bagikan Lewat Link',
        desc: 'Salin tautan unik dan kirim ke WhatsApp, email, atau sosial media.',
      },
    ],
    notes: 'Jelaskan bahwa semua fitur ini gratis dan berjalan di browser pengguna.',
  },
  {
    id: 's7',
    type: 'closing',
    nav: 'Penutup',
    kicker: 'Mulai Sekarang',
    title: 'Siap Membuat Presentasi Anda?',
    subtitle: 'Klik tombol "✏️ Edit Slide" di pojok kanan atas untuk mengganti tulisan ini dengan materi Anda sendiri!',
    foot: 'Mychiara Sliders · Didukung oleh GitHub Pages',
    notes: 'Ajak audiens atau pengguna untuk langsung mencoba klik tombol Edit.',
  },
];
